'''
    How to Create the Custom Exception
'''

try:
    print("I am Try")
finally:
    print("I am Finally")

